/**
 * Source of truth: Google Drive folder "UP Studio"
 * https://drive.google.com/drive/folders/1pFb9mZ9vW9PVQ0tEwcgAE5pAV0KnsFHb
 *
 * Files are served from Google's public CDN. To self-host later, download the
 * files into /public/media and swap the URL builders below — nothing else changes.
 */

export const DRIVE_FOLDER = "https://drive.google.com/drive/folders/1pFb9mZ9vW9PVQ0tEwcgAE5pAV0KnsFHb";

export const DRIVE = {
  logoBlack: "1t4qeR96M1cuyuTiPq-XUlrZWiem4ydbG", // Logo_Black_[Site]_081227.png
  introVideo: "1jf5fbH2Px1AJsnZnMQgdKYQljSyac2F-", // upstudiointro.mp4 (9.8 MB)
  gallery: [
    "1GSmfnzjbWPgAhnCz3SXeaXZzb0na4Zyh", // 021120
    "1htbnC4ECp8bUTyDjWqzMHyU9cb5s220U", // 021140
    "1dtcl8CXaT7dN0rwRNz69ST3vGD6xt2XB", // 021157
    "1yBKbDHliAKBt5HNrdzz6NRTpG8ASe4JV", // 021231
    "1L5BCWt6gH0MOoZC4kMYg466_wlnDggFp", // 021251
    "11c1yRpZXQBvBLY-KsUeu7AM2uIuz9HOQ", // 021324
    "1hHVGaGa40tfovaDLL_4yU8UtHpVg3tSM", // 021339
    "12i6_U64G-TykUX4FvJGNjgFaWWSYiDnA", // 021355
    "1coK53ZRc9ID3YW20_ICM4aqS_KXEDUgJ", // 021438
    "14gSyOll3oVQYPmMaF_yjk9HRT6ezbmfM", // 021454
    "1Vkx8OugCYx1PSf2mA6v9Y1NXiuUBbCA9", // 021518
    "19SKOpjxpJmQfj-bHDuSWWaz9r7F7HR53", // 021642
    "16yrxVHztwh3oex5O7cPxSYWFLeGWfnPf", // 021711
    "193R_fduR1mdPiNnRGYLq4uK1bwKJpd4i", // 021748
    "1PWwNUc9pcBnuB8D18WwCPFGx9tK7UPxv", // 021757
    "1usuQfoXoVpoIHykKnEc6YrV-fqwe3uaW", // 021840
    "1ojpd8y9Ie-ENSzad9gRk9z2GfXEhnw-4", // 021855
  ],
} as const;

/** Resized image via Google's image CDN (works for publicly shared Drive files). */
export const driveImage = (id: string, width = 1600) => `https://lh3.googleusercontent.com/d/${id}=w${width}`;

/** Alternative endpoint used as fallback when lh3 is blocked. */
export const driveThumb = (id: string, width = 1600) => `https://drive.google.com/thumbnail?id=${id}&sz=w${width}`;

/** Direct media stream for <video>. */
export const driveVideo = (id: string) => `https://drive.google.com/uc?export=download&id=${id}`;

export const ASSETS = {
  logo: driveImage(DRIVE.logoBlack, 400),
  logoFallback: driveThumb(DRIVE.logoBlack, 400),
  introVideo: driveVideo(DRIVE.introVideo),
  introPoster: driveImage(DRIVE.introVideo, 1600), // first-frame thumbnail generated by Drive
  heroImage: driveImage(DRIVE.gallery[0], 2000),
};
