import { DRIVE, driveImage, driveThumb } from "./assets";

export type Category = "all" | "fashion" | "portrait" | "sport" | "art";

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: "all", label: "همه" },
  { id: "fashion", label: "مد و فشن" },
  { id: "portrait", label: "پرتره" },
  { id: "sport", label: "ورزشی" },
  { id: "art", label: "هنری" },
];

export interface GalleryItem {
  id: string;
  index: number;
  fileName: string;
  src: string;
  thumb: string;
  fallback: string;
  category: Exclude<Category, "all">;
  title: string;
  alt: string;
}

const pad = (n: number) => String(n).padStart(2, "0");

/**
 * Category metadata copied from the Lovable gallery source.
 * The order is p01 → p17 and therefore matches the local 17 gallery files.
 */
const META: {
  category: GalleryItem["category"];
  title: string;
}[] = [
  { category: "sport", title: "ورزشی ۰۱" },
  { category: "fashion", title: "ادیتوریال ۰۱" },
  { category: "fashion", title: "ادیتوریال ۰۲" },
  { category: "art", title: "هنری ۰۱" },
  { category: "fashion", title: "ادیتوریال ۰۳" },
  { category: "fashion", title: "ادیتوریال ۰۴" },
  { category: "fashion", title: "ادیتوریال ۰۵" },
  { category: "fashion", title: "ادیتوریال ۰۶" },
  { category: "portrait", title: "پرتره ۰۱" },
  { category: "portrait", title: "پرتره ۰۲" },
  { category: "fashion", title: "ادیتوریال ۰۷" },
  { category: "portrait", title: "پرتره ۰۳" },
  { category: "art", title: "هنری ۰۲" },
  { category: "sport", title: "ورزشی ۰۲" },
  { category: "art", title: "هنری ۰۳" },
  { category: "sport", title: "ورزشی ۰۳" },
  { category: "art", title: "هنری ۰۴" },
];

export const GALLERY: GalleryItem[] = DRIVE.gallery.map((fileName, i) => {
  const n = i + 1;
  const m = META[i] ?? { category: "portrait" as const, title: `اثر ${pad(n)}` };

  return {
    id: `p${pad(n)}`,
    index: n,
    fileName,
    src: driveImage(fileName, 2000),
    // Thumbnails are the small WebP files generated by CI, not the original JPG.
    thumb: driveThumb(fileName, 640),
    fallback: driveImage(fileName, 2000),
    category: m.category,
    title: m.title,
    alt: `${m.title} — ${CATEGORIES.find((c) => c.id === m.category)?.label} — آپ استودیو`,
  };
});
